Updating subtitle colors in dark mode
wordplaydev/wordplay pull request #458
Opened 2024-05-08 06:43 UTC by leo3tian

Issue: #399 
Subtitle colors were too dark and violated WCAG guidelines.

Work I did:
Changed the header color from dark gray to white, using the --wordplay-foreground variable in app.html

What the reviewer may need to consider:
From a design standpoint, the reviewer may need to consider whether the color is visually different enough from the rest of the text. The reviewer may also need to consider how this change impacts the rest of the website, other than just the subtitles on the front page. I've provided screenshots at #399, showing how this change impacts other pages. Generally, I think any switch from the previous gray to white should be good for visibility but it's good to check other parts of the website to see if there are any unwanted changes.

2024-05-08 18:43 UTC, joonpiter commented
Hi @leo3tian are you asking for a design review?

2024-05-09 18:27 UTC, amyjko requested changes
This fix definitely resolves the specific issue, but it does so by introducing a different issue: inconsistency between the light and dark modes. This change would mean that headers in light mode are the dark grey color, but headers in dark mode are the foreground color. That breaks consistency between the two light/dark modes.

It seems like the change should be in fixing `--color-dark-grey` in dark mode. Isn't that color problematic _everywhere_ in dark mode, not just headers?

2024-05-29 22:08 UTC, leo3tian commented
Right, it would be smarter to apply changes to `--color-dark-grey` in dark mode instead of changing the value for `--wordplay-header`. I've changed `--color-dark-grey` to be brighter, but the problem now is that there's a discrepancy in color values:
![image](https://github.com/wordplaydev/wordplay/assets/87582530/68e2fe10-a49c-447c-867e-d4db51dcc02c)
After changing `--color-dark-grey`, dark grey now appears to be lighter than light grey and very light grey. I propose that we get rid of light grey and very light grey altogether - `--color-dark-grey` seems to be light enough already for all elements that we would color grey.

2024-06-02 15:59 UTC, amyjko commented
It does create a misalignment between the names of the colors and their relative lightness, but that is common with dark mode: names don't always preserve their semantics when negated for darkness.

Light grey and very light grey are used for other purposes, not just text (e.g., alternating row colors in tables, widget backgrounds). Removing them would break the visual design of those other elements.

2024-10-26 22:06 UTC, amyjko commented
Closing unfinished pull request.

2024-10-26 22:06 UTC, closed without merging