#479 Translating tutorial to traditional Chinese
wordplaydev/wordplay pull request #592
Opened 2024-11-01 16:07 UTC by helenwu95

# Context

The translation of traditional Chinese

## Verification

Need another person to check if there is any content that hasn't translated into traditional Chinese before line 323.

2024-11-01 17:36 UTC, amyjko commented
Hi @helenwu95! Can you clarify what you mean above, about verifying content before line 323? You can see the file and it's contents in `main`. Is there some reason you can't know?

2024-11-01 18:04 UTC, helenwu95 commented
> Hi @helenwu95! Can you clarify what you mean above, about verifying content before line 323? You can see the file and it's contents in `main`. Is there some reason you can't know?


Hi! @amyjko Just to clarify, my current progress on the Traditional Chinese translation is up to line 323, and I’m hoping someone can check that I’ve translated every tutorial up to that point, in case I miss something in my last check. Also, I apologize for misusing the hash earlier.

2024-11-01 23:38 UTC, amyjko commented
I think I'm still unsure what you mean. Are you asking someone else who can code review your traditional Chinese translations, to make sure they are good, or that you didn't miss any translations between line 1-323? (You can check the letter easily, by just looking for English in the lines, which is why I'm confused).

2024-11-02 01:04 UTC, helenwu95 commented
What I mean is that I might need someone to check if I've missed any translations before line 323. In Visual Studio, while I only need to translate the dialogue, the character names and functions, and UI settings are in English and often mixed in with the dialogue, which makes it easy to overlook something. Although I've checked everything twice before submitting, it would be helpful to have someone else review it before merging into the main branch. I will also do a comprehensive check of the translated sections in the end of this quarter, so everything should be fine.

2024-11-02 01:12 UTC, helenwu95 commented
And I just found that there are some parts I didn't translate in Chapter 1, which are the "miss in first chapter (1)." I hope there won’t be any more oversights like that.

2024-11-02 17:01 UTC, amyjko commented
Thanks for the clarification. When I look at lines 1-323, the main content that's not translated is code. It's still using all English names, but should be using Chinese names.

2024-12-06 03:10 UTC, amyjko requested changes
Everything up until line 323 looks translated to me. The one exception is code: all of the example programs are still in English. They should be using the Chinese names, not English names.

2025-01-10 01:06 UTC, amyjko approved these changes

2025-01-10 01:07 UTC, amyjko commented
Just confirming that this PR is not ready to merge, correct? (The tutorial is not done)? I'm going to mark it as a draft.

2025-01-11 05:48 UTC, helenwu95 commented
> Just confirming that this PR is not ready to merge, correct? (The tutorial is not done)? I'm going to mark it as a draft.

Yes, they are not ready to merge. I am still working on translating every character's name, and once finish, I'll @ you again for review. 

And I wonder if we can removed the traditional Chinese tutorial from available option for now, as the tutorial hasn't really been fully translated yet. When I tried the traditional Chinese version, only the first scene is translated.

2025-01-15 21:21 UTC, helenwu95 commented
@amyjko I've updated the name of the character into **Traditional Chinese(English term)** to the latest progress (line 637). I've checked the content before line 637, so if there isn't another portion of tutorial before line 637 is untranslated, I'll move forward and translate the content after line 637.

2025-01-16 00:49 UTC, amyjko commented
@helenwu95 That seems like a reasonable convention to follow, per our conversation.

2025-01-30 23:43 UTC, amyjko commented
@helenwu95 Is this still a draft? If so, please mark it as one, so I know that it's not ready for review.

2025-01-31 06:00 UTC, helenwu95 commented
> @helenwu95 Is this still a draft? If so, please mark it as one, so I know that it's not ready for review.

The line until 658 should be ready to review!

2025-01-31 15:04 UTC, amyjko commented
When a PR is marked "Draft", it means its not ready to merge. When there is no "Draft" label, it means its ready to merge. It doesn't sound like you're ready to merge.

2025-01-31 17:33 UTC, helenwu95 commented
> When a PR is marked "Draft", it means its not ready to merge. When there is no "Draft" label, it means its ready to merge. It doesn't sound like you're ready to merge.

Understand, it is not ready to be reviewed yet, I am still working on translation. I'll comment again when it is ready to review.

2025-05-30 03:21 UTC, merged