#585: Create end2end test for expand/exit buttons in project page
wordplaydev/wordplay pull request #620
Opened 2024-12-09 23:34 UTC by yue7xu

Create layout_02_fullscreen_expand_exit.spec.ts(a suit of end to end test of expand/exit full screen for four tiles). ignore other adjustment(failture to add uiid)

# Context

This pull request addresses Issue #585 by creating an end-to-end test suite to verify the expand and exit fullscreen functionality for four tiles (palette, guide, stage, source) on the project page.

The test ensures:
Each tile's expand button successfully transitions the tile to fullscreen mode.
The exit fullscreen button properly reverts the tile to its original state.
The functionality works consistently across all four tiles.

## Related issues

-   Related Issue #585 

## Verification

Run the test suite using the Playwright test runner, and all tests pass without errors.

## Checklist

- [x] Created new test file layout_02_fullscreen_expand_exit.spec.ts.
- [x] Verified functionality for all four tiles (palette, guide, stage, source).
- [x] Ran tests locally using Playwright to ensure no failures.
- [ ] Expand for additional tiles or sources that users may dynamically create.
- [ ] Identify and Categorize Untested UI Components(e.g., navigation, buttons, modals, sliders).

2024-12-12 02:02 UTC, amyjko requested changes
This PR has multiple files that are updated that should not be updated or included in this PR:

* `package.json`
* `package-lock.json`
* `vite.config`...

The PR also creates a redundant end-to-end test folder; everything should be organized in `/tests/end2end`, rather than creating a new place to store tests. That includes the example test should not be included; that is not part of our project.

The `test-examples1 folder you have added should also be removed; that is not part of the project.

There should not be additions to the `SerializedLayout` type. That is the data that is stored between browser sessions and tabs, and it should not contain test information.

Please address all of these issues and then I'll re-review. Thanks!

2025-06-21 15:08 UTC, amyjko commented
@yue7xu, are you still working on this PR? I left comments in December, but you never replied. It's okay to say no, just post an update so we can plan.

2025-06-22 08:41 UTC, yue7xu commented
Hi @amyjko, thank you for following up, and I apologize for not responding earlier. After some reflection, I realized I have lost track of the context around my earlier contributions and do not feel confident picking this back up. I also want to focus on other issues where I feel I can contribute more meaningfully. I’m truly sorry for leaving this unfinished and not communicating this sooner. Please feel free to close or reassign it as needed. Thank you again for your feedback and guidance.

2025-06-23 15:46 UTC, amyjko commented
Thanks for the update. I'll review, see if the work is salvageable, and either finish it or close the PR.

2025-06-28 15:48 UTC, amyjko reviewed
I've reviewed this, and it's drifted too far from main to be salvageable. It would be easier to rewrite these tests from scratch then to modify the tests as written. I'm going to close this PR.

2025-06-28 15:48 UTC, closed without merging